version: '3.8'
services:
  backend:
    build: ./backend
    volumes:
      - .:/code
    environment:
      - DATABASE_URL=mysql://root:aTh5ao8oLi9guizu@db:3306/library
    ports:
      - 8080:80
    depends_on:
      - db
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=library
      - MYSQL_ROOT_PASSWORD=aTh5ao8oLi9guizu
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  db:
    driver: local